### ISSUE TITLE
Fatal crash

### ISSUE THREAD

**Issue by aakashbapna** [huitingyeong/bluetooth_enable#2]
Received this via Crashlytics, will share more details as I get from user.

Error Message - 
```
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { }} to activity {com.udaan.calculator.android/com.udaan.calculator.android.MainActivity}: java.lang.IllegalStateException: Reply already submitted
```

Stack -
```
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.a(MethodChannel.java:14)
       **at com.hui.bluetooth_enable.BluetoothEnablePlugin.a(BluetoothEnablePlugin.java:37)**
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.a(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.a(FlutterEngineConnectionRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.a(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8249)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4968)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5016)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7561)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

**Comment by insertjokehere** [comment]
I am also seeing this issue with some users, did you ever find a fix? or at least a root cause?

**Comment by MrCsabaToth** [comment]
Here's how a regular Play Store crash stack looks:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5506)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5547)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:155)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:238)
  at com.hui.bluetooth_enable.BluetoothEnablePlugin.onActivityResult (BluetoothEnablePlugin.java:98)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:739)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:426)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:677)
  at io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:624)
  at android.app.Activity.dispatchActivityResult (Activity.java:8541)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5499)
```

**Comment by MrCsabaToth** [comment]
Notes: https://stackoverflow.com/questions/65666404/java-lang-illegalstateexception-reply-already-submitted-when-trying-to-call
Maybe `result.success("true");` and `result.success("false");` needs to be wrapped in a `runOnUiThread`? I haven't tried it yet.

**Comment by insertjokehere** [comment]
The only way I could reliably reproduce this was to make it so there were two instances of the Bluetooth prompt on screen at once. When the user dismissed the second instance, the app would crash with the same error. Not sure if its the same root cause, but I'm working around it by making sure we don't prompt the user more than once

**Comment by MrCsabaToth** [comment]
@insertjokehere You mean from two separate apps at the same time? Two apps which are both Flutter based and use the same plugin?

**Comment by insertjokehere** [comment]
@MrCsabaToth no, just the one app. This was a bug where the user could press a button that would trigger the Bluetooth prompt while a task was running that would trigger the prompt after a few seconds - if you got the timing wrong, you could press the button to trigger the prompt before the task realised you didn't have Bluetooth turned on, so the app ended up asking you to turn Bluetooth on a second time before you had a chance to deal with the first prompt

**Comment by MrCsabaToth** [comment]
"This was a bug" - is that bug ticketed? Is it fixed but there's some relapse happening here?

**Comment by insertjokehere** [comment]
"This was a bug" as in a bug in our code, not in the library code

**Comment by MrCsabaToth** [comment]
@insertjokehere Thanks, I should revise my code. In my case Bluetooth is an essential feature to my app so I kick in the `bluetooth_enable` during the start. But maybe users could disable the bluetooth while the app is in the background or something. I should experiment. But it'd still be good to have a solution at the plugin level as well to make it more robust?

**Comment by huitingyeong** [comment]
HI I have looked through the error reported. Let me see if I can replicate it.

**Comment by MrCsabaToth** [comment]
> Hi I have looked through the error reported. Let me see if I can replicate it.

FYI this crash happened only a couple of times in the wild in my app, so it's a rare issue. I was not able to replicate it on my end.

**Comment by MrCsabaToth** [comment]
It'd be beneficial to include java.lang.IllegalStateException in the title of the issue because "Fatal crash" is too broad.

**Comment by MrCsabaToth** [comment]
Lately I got some NPE (NullPointerException) also in release from Android 12 phones, also inside `onActivityResult` just like the `IllegalStateException`:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5304)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5343)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:54)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2214)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7842)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: 
  at com.hui.bluetooth_enable.BluetoothEnablePlugin.onActivityResult (BluetoothEnablePlugin.java:98)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:739)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:426)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:677)
  at io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:624)
  at android.app.Activity.dispatchActivityResult (Activity.java:8382)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5297)
```
